---
- name: Force legacy mode if not using systemd
  when:
    - ansible_service_mgr != "systemd"
  ansible.builtin.set_fact:
    resolv_mode: legacy

- name: Get existing /etc/resolv.conf file info
  register: sym
  ansible.builtin.stat:
    path: /etc/resolv.conf


- name: Legacy mode
  when:
    - resolv_mode == "legacy"
  block:
    - name: Disbale systemd-resolved
      become: true
      when:
        - ansible_service_mgr == "systemd"
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: stopped
        force: true
        daemon_reload: true
        enabled: false
        masked: true

    - name: Delete existing /etc/resolv.conf link
      become: true
      when:
        - sym.stat.islnk is defined
        - sym.stat.islnk
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        force: true

    - name: Create legacy /etc/resolv.conf file
      become: true
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: "0644"
        owner: root
        group: root


- name: Resolved mode
  when:
    - resolv_mode == "resolved"
  block:
    - name: Create systemd-resolved drop-in dir
      become: true
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create systemd-resolved config file
      become: true
      ansible.builtin.template:
        src: resolved.conf.j2
        dest: /etc/systemd/resolved.conf.d/resolved.conf
        mode: "0644"
        owner: root
        group: root

    - name: Delete legacy /etc/resolv.conf file
      become: true
      when:
        - sym.stat.isreg is defined
        - sym.stat.isreg
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        force: true

    - name: Enable systemd-resolved.service
      become: true
      when:
        - ansible_service_mgr == "systemd"
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: started
        force: true
        daemon_reload: true
        enabled: true
        masked: false

    - name: Create symlink /etc/resolv.conf to /run/systemd/resolve/resolv.conf
      become: true
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link

    - name: Restart systemd-resolved
      become: true
      when:
        - ansible_service_mgr == "systemd"
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: restarted
        force: true
        daemon_reload: true
