---
- name: Force legacy mode if not using systemd
  ansible.builtin.set_fact:
    resolv_mode: legacy
  when: ansible_service_mgr != "systemd"

- name: Get existing /etc/resolv.conf file info
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: sym


- name: Legacy mode
  when: resolv_mode == "legacy"
  block:
    - name: Disbale systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: stopped
        force: true
        daemon_reload: true
        enabled: false
        masked: true
      when: ansible_service_mgr == "systemd"

    - name: Delete existing /etc/resolv.conf link
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        force: true
      when: sym.stat.islnk is defined and sym.stat.islnk

    - name: Create legacy /etc/resolv.conf file
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: "0644"
        owner: root
        group: root


- name: Resolved mode
  when: resolv_mode == "resolved"
  block:
    - name: Create systemd-resolved drop-in dir
      ansible.builtin.file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create systemd-resolved config file
      ansible.builtin.template:
        src: resolved.conf.j2
        dest: /etc/systemd/resolved.conf.d/resolved.conf
        mode: "0644"
        owner: root
        group: root

    - name: Delete legacy /etc/resolv.conf file
      ansible.builtin.file:
        path: /etc/resolv.conf
        state: absent
        force: true
      when: sym.stat.isreg is defined and sym.stat.isreg

    - name: Enable systemd-resolved.service
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: started
        force: true
        daemon_reload: true
        enabled: true
        masked: false
      when: ansible_service_mgr == "systemd"

    - name: Create symlink /etc/resolv.conf to /run/systemd/resolve/resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        state: link

    - name: Restart systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: restarted
        force: true
        daemon_reload: true
      when: ansible_service_mgr == "systemd"
